# rucio
- job_name: "rucio-dev"
  scrape_interval: 60s
  static_configs:
  - targets: [ "cms-rucio-stats-dev.cern.ch" ]
  - labels: {"env": "dev", "job": "reqmgr2-dev"}
- job_name: "rucio-testbed"
  scrape_interval: 60s
  static_configs:
  - targets: [ "cms-rucio-stats-testbed.cern.ch" ]
  - labels: {"env": "testbed", "job": "reqmgr2-testbed"}
- job_name: "rucio-sync"
  scrape_interval: 60s
  static_configs:
  - targets: [ "cms-rucio-stats-sync.cern.ch" ]
  - labels: {"env": "sync", "job": "reqmgr2-sync"}
- job_name: "rucio-int"
  scrape_interval: 60s
  static_configs:
  - targets: [ "cms-rucio-stats-int.cern.ch" ]
  - labels: {"env": "int", "job": "reqmgr2-int"}

