apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    k8s-app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    protocol: TCP
    nodePort: 32001
    targetPort: ui
  selector:
    k8s-app: kibana


