image:
  repository: rucio/rucio-server
  tag: release-1.23.8_py3
  # tag: release-1.23.8
  pullPolicy: Never

# For NGINX ingress. Eventually becomes plain server
replicaCount: 1
authReplicaCount: 1
traceReplicaCount: 1

exposeErrorLogs:
  server: True
  authServer: True
  traceServer: True

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

# Use http worker mode and elsewhere configure database connections for Oracle Database Resident Connection Pool (DRCP)
httpd_config:
  encoded_slashes: "True"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/frontend-entry-points: http, https
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - pic01-rucio-server.pic.es
  tls: 
    - secretName: rucio-server.tls-secret

# Auth server runs on 443 and needs the connection forwarded straight through

useSSL:
  authServer: false

authIngress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/frontend-entry-points: http, https
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  path:
  hosts: 
    - pic01-rucio-server-auth.pic.es
  tls:
    - secretName: rucio-server.tls-secret

config:
  database:
    default: "postgresql://rucio:secret@postgres-postgresql/rucio"
    schema: "test"
  policy:
    # config.permission.policy: (default "generic")
    # permission: "generic"
    permission: "pic-policy"

additionalSecrets:
  policy:
    secretName: policy
    mountPath: /usr/local/lib/python3.6/site-packages/rucio/common/schema/pic-policy.py
    subPath: pic-policy.py
