# Default values for rucio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## replicaCount gives the number of server pods to run
replicaCount: 1

# When set, run extra busybox containers in the relevant pods to also expose the error logs
exposeErrorLogs: True

service:
  type: NodePort
  # Run the webui server on port 443 instead of 80 and accept X509 certificates and proxies
  useSSL: true
  port: 443
  targetPort: https
  portName: https

image:
  #repository: rucio/rucio-ui
  # Needed until official images are built correctly
  #repository: cmssw/rucio-ui
  tag: release-1.23.8

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  path: /
  hosts: 
    - "pic01-rucio-server-trace.pic.es"    
  tls: 
    - secretName: rucio-server.tls-secret

proxy:
  rucioProxy: "pic01-rucio-server.pic.es"
  rucioProxyScheme: "https"
  rucioAuthProxy: "pic01-rucio-server-auth.pic.es"
  rucioAuthProxyScheme: "https"  

## values used to configure Rucio
config:
  database:
    default: "postgresql://rucio:secret@postgres-postgresql/rucio"
    schema: "test"
