apiVersion: v1
kind: Service
metadata:
  labels:
    apps: psql-exporter-service
  name: psql-exporter-service
  namespace: prod-rucio-test
spec:
  ports:
  - name: fixed-port
    protocol: TCP
    port: 80 # CLUSTERIP PORT
    targetPort: 9187 # POD PORT WHICH APPLICATION IS RUNNING ON 
    nodePort: 30570 # HERE!
  externalIPs:
  - 192.168.96.84
  selector: 
    app: prometheus-postgres-exporter
    release: psql
  sessionAffinity: None
  type:	NodePort


