apiVersion: batch/v1
kind: CronJob
metadata:
  name: fts-renew
  namespace: ${K8S_NAMESPACE}
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: bruzzese/fts-renew
            env:
            - name: ftsserver
              value: ${FTS_NAME}
            command: ["/bin/bash"]
            args: ["/fts/renew_fts_delegation.sh"]
            volumeMounts:
            - name: usercert
              mountPath: /etc/grid-security/usercert.pem
              subPath: hostcert.pem
            - name: userkey
              mountPath: /etc/grid-security/userkey.pem
              subPath: hostkey.pem
          restartPolicy: OnFailure
          volumes:
          - name: usercert
            secret:
              secretName: ${RELEASE_NAME}-server-hostcert
              defaultMode: 0600
          - name: userkey
            secret:
              secretName: ${RELEASE_NAME}-server-hostkey
              defaultMode: 0400

