---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rucio-psql-pvc-2
  namespace: prod-rucio-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-rbd-sc
  volumeMode: Filesystem
