---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucio-postgresql-2
  labels:
    app: postgres-2
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-2
  template:
    metadata:
      labels:
        app: postgres-2
        tier: data
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube01
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: rucio-psql-pvc
      - name: pg-data
        emptyDir: {}

      nodeSelector:
        kubernetes.io/hostname: kube01
      containers:
      - name: postgres
        image: postgres:13.3
        imagePullPolicy: IfNotPresent
        args: 
        - postgres
        - -p 5432
        - -c
        - max_connections=1000
        - -c
        - shared_buffers=1024MB 

        env:
        - name: POSTGRES_DB
          value: rucio
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: POSTGRES_USER
          value: rucio
        - name: POSTGRES_PASSWORD
          value: secret
        - name: RUCIO_DB_DUMP
          value: /rucio/rucio-db.dump

        ports:
        - containerPort: 5432 

        volumeMounts:
        - name: postgresdb
          mountPath: /rucio
        - name: pg-data
          mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: rucio-postgresql-2
spec:
  type: ClusterIP
  selector:
    app: postgres-2
  ports:
  - port: 5432


